language: python
python:
# - "3.3" # ignored due to wasp-general limits
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  - coverage run --source wasp_backup -m py.test tests/

after_script:
  - coveralls
